REM S1 2DDS 2018 - 2019
REM OLIVER JACK SHADBOLT 
REM ********************

PROMPT 1.4.1 QUERY
SELECT
	SUBSTR(FIRST_NAME, 1, 2) FN, 
	LAST_NAME, 
	HIRE_DATE,
	ROUND(SALARY * 0.7779)
FROM
	OEHR_EMPLOYEES
WHERE
	SUBSTR(LAST_NAME, 1, 1) = 'M'
AND
	HIRE_DATE > '21-FEB-1998'
ORDER BY
	HIRE_DATE ASC;

PROMPT 1.4.2 QUERY
SELECT
	OEHR_COUNTRIES.COUNTRY_ID ID,
	REGION_ID,
	COUNT(LOCATION_ID)
FROM
	OEHR_LOCATIONS,
	OEHR_COUNTRIES
WHERE
	OEHR_LOCATIONS.COUNTRY_ID (+) = OEHR_COUNTRIES.COUNTRY_ID
GROUP BY
	OEHR_COUNTRIES.COUNTRY_ID,
	REGION_ID
ORDER BY
	ID DESC;

PROMPT 1.4.3 QUERY
SELECT
	DEPARTMENT_NAME,
	COUNTRY_NAME,
	CITY
FROM
	(
		SELECT DISTINCT
			DEPARTMENT_NAME,
			OEHR_DEPARTMENTS.DEPARTMENT_ID,
			LOCATION_ID
		FROM
			OEHR_EMPLOYEES, OEHR_DEPARTMENTS
		WHERE
			OEHR_EMPLOYEES.DEPARTMENT_ID = OEHR_DEPARTMENTS.DEPARTMENT_ID
		AND
			JOB_ID = 'AD_VP'
	) 
	T1,
	(
		SELECT DISTINCT
			OEHR_DEPARTMENTS.DEPARTMENT_ID
		FROM
			OEHR_EMPLOYEES, OEHR_DEPARTMENTS
		WHERE
			OEHR_EMPLOYEES.DEPARTMENT_ID = OEHR_DEPARTMENTS.DEPARTMENT_ID
		AND
			JOB_ID = 'AD_PRES'
	) 
	T2,
	OEHR_LOCATIONS, 
	OEHR_COUNTRIES
WHERE
	T1.DEPARTMENT_ID = T2.DEPARTMENT_ID
AND
	T1.LOCATION_ID = OEHR_LOCATIONS.LOCATION_ID
AND
	OEHR_LOCATIONS.COUNTRY_ID = OEHR_COUNTRIES.COUNTRY_ID
ORDER BY
	COUNTRY_NAME,
	DEPARTMENT_NAME,
	CITY;

PROMPT 1.4.4 QUERY
SELECT
	EMPLOYEE_ID,
	TRUNC(SYSDATE - HIRE_DATE, 1)
FROM
	(
		SELECT
			*
		FROM
			OEHR_EMPLOYEES
		ORDER BY
			HIRE_DATE DESC
	)
WHERE
	ROWNUM <= 4
ORDER BY
	HIRE_DATE ASC;